### ISSUE TITLE
MacOS download of offline app doesn't unzip

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/pxt-ev3#858] opened 2019-05-02 09:05 UTC
**Describe the bug**
The zip file for the offline editor for Mac doesn't unzip, it gives an error.

**To Reproduce**
1. Go to https://makecode.microbit.org/offline-app
2. Agree the terms and conditions
3. Download the MacOS app
4. It will fail to unzip

**Expected behavior**
The download should unzip successfully

**Screenshots**
![2019-05-02_10-03-42](https://user-images.githubusercontent.com/1710385/57065539-a9840400-6cc1-11e9-9177-ea830fc1507f.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4 (Mojave)
 - Browser: Safari
 - Version: 12.1

**Additional context**

**Comment by abchatra** [comment] 2019-05-02 16:55
@jwunderl can you try to reproduce this?

**Comment by jwunderl** [comment] 2019-05-02 17:32
It works for me when downloading it from chrome and manually unzipping it, but failed the first time I tried downloading from safari (though trying to download it again consistently produced valid apps). 

For completeness; mine's a MBP 15in 2018 / 10.14.4 (Mojave), using `unarchiver` as my default unzip utility.

**Comment by abchatra** [comment] 2019-05-02 18:36
@jimbobbennett does it fail to download repeatedly?

**Comment by jimbobbennett** [comment] 2019-05-03 11:51
Yup - fails every time on Safari.

<img width="320" alt="2019-05-03_12-48-26" src="https://user-images.githubusercontent.com/1710385/57135589-d3acf300-6da1-11e9-84f8-992011ce7a0d.png">

Fails on Chrome as well - the downloads can't be unzipped by the default MacOS unzip tool - Archive Utility..

**Comment by pelikhan** [comment] 2019-08-30 12:39
@abchatra is this fixed?

**Comment by abchatra** [comment] 2019-08-30 17:17
This got fixed in microbit when we released a new payload. Likely cdn caching issue.

**Comment by pelikhan** [comment] 2019-10-10 00:38
@jimbobbennett please try again and reopen if the issue persists.

**Closed by pelikhan** 2019-10-10 00:38 UTC
